--名称
appname="迷你开发者工具箱"
--版本号
appver="2.4.4"
--版本
appcode="244"
--SDK
appsdk="21"
--包名
packagename="com.mini.dev.toolbox"
--调试模式
debugmode=false
--应用权限
user_permission={
  "DOWNLOAD_WITHOUT_NOTIFICATION",
  "GET_PACKAGE_SIZE",
  "INTERNET",
  "READ_EXTERNAL_STORAGE",
  "SYSTEM_ALERT_WINDOW",
  "VIBRATE",
  "WRITE_EXTERNAL_STORAGE",
}
--跳过编译
skip_compilation={

}